name: wiebitte

on:
  push:
    paths:
      - '.github/workflows/antics.original.yml'
      
jobs:
  wiebitte:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        repository: ${{ github.repository }}
        token: ${{ secrets.LUMINETHONK }}

    - name: AquaCriUGUU
      run: |
        function generateyml() {     [ "$1" ] && iteration="$1" || iteration=20;     originalfile=".github/workflows/$2.original.yml";     resultfile=".github/workflows/$2.yml";     linenum=`cat "$originalfile" | grep -n "Pre-processing" | tail -1 | grep -Eo "[0-9]+"`;     cat "$originalfile" | head -"$((linenum-1))" | sed "s/ (original//g" > "$resultfile";     for iter in `seq 2 $iteration`;     do         cat "$originalfile" | tail +"$((linenum))" | sed "s/partplaceholder/part$iter/g;s/Partplaceholder/Part $iter/g" >> "$resultfile";         echo >> "$resultfile";     done; }; generateyml 114 "antics";
        git config --global user.name '${{ github.actor }}'
        git config --global user.email '${{ github.actor }}@users.noreply.github.com'
        git commit -am "Signora is worst Futui Harbinger desu"
        git remote set-url origin https://x-access-token:${{ secrets.LUMINETHONK }}@github.com/${{ github.repository }}
        git push
